### ISSUE TITLE
Module 1. Exercise 4. "api/locations" path on Azure doesn't work

### ISSUE THREAD

**Issue by 01vadim10** [MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices#100]
I made and checked all instructions from **Module 1**. Website was published but when I go to **https://mywebsitename.azurewebsites.net/api/locations** it shows error:
`<Error>
<Message>An error has occurred.</Message>
</Error>`
On a local machine with the same connection string, everything works.
I also tried Release and Debug configs for Publish
I followed by instructions from [here](https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices/blob/master/Instructions/20487C/20487C_MOD01_LAK.md)

**Comment by nadav-har-tzvi** [comment]
@01vadim10  Thanks and sorry for the late reply. The issue was that Azure SQL server instances are by default closed to any incoming connection and you need to explicitly enable incoming connections from other Azure services (e.g. an application hosted as a Web App)
